---
version: '3.3'
services:
  zeppelin:
    container_name: zeppelin
    image: apache/zeppelin:0.7.3
    environment:
      CLASSPATH: ":/zeppelin/drivers/*"
    volumes:
      - "./interpreter.json:/zeppelin/conf/interpreter.json"
      - "./drivers:/zeppelin/drivers"
    ports:
      - "8080:8080"
