---

Description: "Sample EMR cluster with minimal configuration."

Parameters:
  ClusterName:
    Description: The EMR cluster name.
    Type: String
    Default: emr-sample

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances.
    Type: AWS::EC2::KeyPair::KeyName

  SubnetId:
    Description: The subnet to launch the nodes.
    Type: AWS::EC2::Subnet::Id

  AdditionalMasterSecurityGroups:
    Description: List of extra security groups for Master nodes.
    Type: List<AWS::EC2::SecurityGroup::Id>

  AdditionalSlaveSecurityGroups:
    Description: List of extra security groups for Slave nodes.
    Type: List<AWS::EC2::SecurityGroup::Id>

  LogUri:
    Description: S3 location for the EMR logs.
    Type: String

Resources:
  EmrCluster:
    Type: "AWS::EMR::Cluster"
    Properties:
      Name: !Ref ClusterName
      ReleaseLabel: "emr-5.13.0"
      Applications:
        - Name: Ganglia
        - Name: Spark
        - Name: Zeppelin
        - Name: Hadoop
        - Name: Tez
        - Name: Hive
      EbsRootVolumeSize: "16"
      Instances:
        AdditionalMasterSecurityGroups: !Ref AdditionalMasterSecurityGroups
        AdditionalSlaveSecurityGroups: !Ref AdditionalSlaveSecurityGroups
        MasterInstanceGroup:
          Name: "Master Instance Group"
          InstanceType: "m4.large"
          InstanceCount: "1"
          EbsConfiguration:
            EbsBlockDeviceConfigs:
              - VolumeSpecification:
                  SizeInGB: "32"
                  VolumeType: gp2
          Market: "ON_DEMAND"
        CoreInstanceGroup:
          Name: "Core Instance Group"
          InstanceType: "r4.xlarge"
          InstanceCount: "2"
          EbsConfiguration:
            EbsBlockDeviceConfigs:
              - VolumeSpecification:
                  SizeInGB: "32"
                  VolumeType: gp2
          Market: "SPOT"
          BidPrice: "0.13"
        Ec2KeyName: !Ref KeyName
        Ec2SubnetId: !Ref SubnetId
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      LogUri: !Ref LogUri
      VisibleToAllUsers: "true"
